### ISSUE TITLE
plugin new!!!!!

### ISSUE THREAD

**Issue by dawatr** [OguzhanUmutlu/FriendSystem#2]
Hello, if you can create a plugin for the registry, login
thanks a lot

**Comment by OguzhanUmutlu** [comment]
Like SimpleAuth plugin??

**Comment by dawatr** [comment]
yes

**Comment by OguzhanUmutlu** [comment]
> yes

Like what you want me to do ? there is already a simpleauth plugin
what are the differences?

**Comment by OguzhanUmutlu** [comment]
and sorry for 25 days :d
