### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by WinterHellMC** [OguzhanUmutlu/FriendSystem#8]
When someone tries to accept the friend request they get internal server error
ErrorException: "Undefined variable: friend" (EXCEPTION) in "plugins/FriendSystem.phar/src/OguzhanUmutlu/Friends/FriendCommand" at line 282

**Comment by OguzhanUmutlu** [comment]
first do not spam second i am gonna fix it

**Comment by OguzhanUmutlu** [comment]
fixed in github.
